# Generated by Django 4.0.3 on 2022-08-09 06:00

import core.imggenerate
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('distributer', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False, verbose_name='Проверено?')),
                ('payment_left', models.FloatField(blank=True, null=True, verbose_name='Оставшаяся сумма')),
            ],
            options={
                'verbose_name': 'Фермер',
                'verbose_name_plural': 'Фермеры',
                'ordering': ('-id',),
            },
            bases=('user.user',),
        ),
        migrations.CreateModel(
            name='SaleFarmerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameRu', models.CharField(max_length=500, verbose_name='Название на русском')),
                ('nameKg', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название на кыргызском')),
                ('nameEn', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название на английском')),
            ],
            options={
                'verbose_name': 'Категория продукт для продажи фермерам',
                'verbose_name_plural': 'Категории продукт для продажи фермерам',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='SaleFarmerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('cost', models.FloatField(default=0, verbose_name='Цена')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.imggenerate.all_image_file_path, verbose_name='Фото')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer.salefarmercategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт для продажи фермерам',
                'verbose_name_plural': 'Продукты для продажи фермерам',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='FarmerOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата')),
                ('comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='Комментарий')),
                ('status', django_fsm.FSMIntegerField(choices=[(1, 'Новый'), (2, 'Упаковывается'), (3, 'В пути'), (4, 'Доставлено'), (5, 'Отказано'), (6, 'Отказано')], default=1, verbose_name='Статус')),
                ('totalCost', models.IntegerField(default=0, verbose_name='Общая сумма')),
                ('distributer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='distributer.distributer', verbose_name='Дистрибьютер')),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer.farmer', verbose_name='Фермер')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer.salefarmeritem', verbose_name='Товар')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer.farmerorders')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
