# Generated by Django 4.0.3 on 2022-08-08 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_alter_farmer_payment_left_alter_farmer_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False, verbose_name='Проверено?')),
                ('payment_left', models.FloatField(blank=True, null=True, verbose_name='Оставшаяся сумма')),
            ],
            options={
                'verbose_name': 'Фермер',
                'verbose_name_plural': 'Фермеры',
                'ordering': ('-id',),
            },
            bases=('user.user',),
        ),
    ]
