# Generated by Django 4.0.3 on 2022-09-21 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_city_options_alter_district_options_and_more'),
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salefarmeritem',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_item_district', to='user.district', verbose_name='Район'),
        ),
    ]
