# Generated by Django 4.0.3 on 2022-08-08 14:59

import core.imggenerate
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleFarmerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameRu', models.CharField(max_length=500, verbose_name='Название на русском')),
                ('nameKg', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название на кыргызском')),
                ('nameEn', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название на английском')),
            ],
            options={
                'verbose_name': 'Категория продукт для продажи фермерам',
                'verbose_name_plural': 'Категории продукт для продажи фермерам',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='SaleFarmerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('cost', models.FloatField(default=0, verbose_name='Цена')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.imggenerate.all_image_file_path, verbose_name='Фото')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer.salefarmercategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт для продажи фермерам',
                'verbose_name_plural': 'Продукты для продажи фермерам',
                'ordering': ('-id',),
            },
        ),
    ]
