# Generated by Django 4.1.4 on 2022-12-30 19:53

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_salefarmeritem_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='farmer_type',
            field=django_fsm.FSMIntegerField(blank=True, choices=[(1, 'Мелкий'), (2, 'Средний'), (3, 'Крупный')], null=True),
        ),
    ]
