# Generated by Django 4.0.3 on 2022-08-08 16:14

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('distributer', '0001_initial'),
        ('farmer', '0002_salefarmercategory_salefarmeritem'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата')),
                ('comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='Комментарий')),
                ('status', django_fsm.FSMIntegerField(choices=[(1, 'Новый'), (2, 'Упаковывается'), (3, 'В пути'), (4, 'Доставлено'), (5, 'Отказано'), (6, 'Отказано')], default=1, verbose_name='Статус')),
                ('totalCost', models.IntegerField(default=0, verbose_name='Общая сумма')),
                ('distributer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='distributer.distributer', verbose_name='Дистрибьютер')),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer.farmer', verbose_name='Фермер')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer.salefarmeritem', verbose_name='Товар')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer.farmerorders')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
