# Generated by Django 4.0.3 on 2023-03-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_model1cuser_alter_user_type'),
        ('farmer', '0004_alter_farmer_farmer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='salefarmeritem',
            name='districts',
            field=models.ManyToManyField(blank=True, null=True, related_name='farmer_item_districts_list', to='user.district', verbose_name='Район'),
        ),
        migrations.AddField(
            model_name='salefarmeritem',
            name='is_sale',
            field=models.BooleanField(default=False, verbose_name='Распродажа'),
        ),
        migrations.AddField(
            model_name='salefarmeritem',
            name='sale_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена распродажи'),
        ),
    ]
