# Generated by Django 4.0.3 on 2023-04-01 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0006_remove_cartitems_order_farmerorders_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerorders',
            name='items',
        ),
        migrations.AddField(
            model_name='cartitems',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer.farmerorders'),
        ),
    ]
