# Generated by Django 4.0.3 on 2023-08-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0009_farmer_onec_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='cardNumber',
            field=models.CharField(blank=True, max_length=200, verbose_name='Номер карты'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='milkCost',
            field=models.FloatField(default=0, verbose_name='Стоимость молока'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='paymentType',
            field=models.CharField(choices=[('card', 'С картой'), ('cash', 'С наличными')], default='card', max_length=10, verbose_name='Тип оплаты'),
        ),
    ]
