# Generated by Django 4.0.3 on 2023-09-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0010_farmer_cardnumber_farmer_milkcost_farmer_paymenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelCows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Корова',
                'verbose_name_plural': 'Коровы',
            },
        ),
        migrations.AddField(
            model_name='farmer',
            name='cows',
            field=models.ManyToManyField(blank=True, to='farmer.modelcows', verbose_name='Коровы'),
        ),
    ]
