# Generated by Django 4.0.3 on 2023-09-13 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0011_modelcows_farmer_cows'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelcows',
            old_name='name',
            new_name='cow_id',
        ),
    ]
