# Generated by Django 4.0.3 on 2023-11-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0012_rename_name_modelcows_cow_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата регистрации'),
        ),
    ]
