# Generated by Django 4.0.3 on 2022-08-09 06:01

import core.imggenerate
from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.imggenerate.all_image_file_path, verbose_name='Фото')),
                ('category', django_fsm.FSMIntegerField(choices=[(1, 'Молочная продукция'), (2, 'Национальные напитки'), (3, 'Прохладные напитки')], verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар для ВЕБ',
                'verbose_name_plural': 'Товары для ВЕБ',
                'ordering': ('-id',),
            },
        ),
    ]
