# Generated by Django 4.0.3 on 2022-08-08 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_delete_farmer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Распределитель',
                'verbose_name_plural': 'Распределители',
                'ordering': ('-id',),
            },
            bases=('user.user',),
        ),
    ]
