# Generated by Django 4.0.3 on 2022-08-10 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('id',), 'verbose_name': 'Город/Область', 'verbose_name_plural': 'Города/Области'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ('id',), 'verbose_name': 'Район', 'verbose_name_plural': 'Районы'},
        ),
        migrations.AlterField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Статус активации?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_city', to='user.city', verbose_name='Город/Область'),
        ),
        migrations.AlterField(
            model_name='user',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_district', to='user.district', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(max_length=200, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.FloatField(default=5, verbose_name='Рейтинг'),
        ),
    ]
