# Generated by Django 4.0.3 on 2022-08-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='payment_left',
            field=models.FloatField(blank=True, null=True, verbose_name='Оставшаяся сумма'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Проверено?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Актив?'),
        ),
    ]
