# Generated by Django 4.0.3 on 2022-08-02 20:02

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='type',
            field=django_fsm.FSMIntegerField(choices=[(1, 'Пользователь Компании'), (2, 'Фермер'), (3, 'Поставшик')], default=1),
        ),
        migrations.AddField(
            model_name='distributer',
            name='type',
            field=django_fsm.FSMIntegerField(choices=[(1, 'Пользователь Компании'), (2, 'Фермер'), (3, 'Поставшик')], default=3),
        ),
        migrations.AddField(
            model_name='farmer',
            name='type',
            field=django_fsm.FSMIntegerField(choices=[(1, 'Пользователь Компании'), (2, 'Фермер'), (3, 'Поставшик')], default=2),
        ),
    ]
