# Generated by Django 4.0.3 on 2022-08-08 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_accepted_farmer_alter_payment_farmer'),
        ('user', '0002_alter_farmer_payment_left_alter_farmer_verified_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Farmer',
        ),
    ]
