# Generated by Django 4.1.4 on 2022-12-30 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_laborantuser_alter_user_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LaborantUser',
        ),
    ]
