# Generated by Django 4.0.3 on 2022-08-08 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_accepted_distributor'),
        ('user', '0003_delete_farmer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Distributer',
        ),
    ]
