# Generated by Django 4.0.3 on 2023-03-24 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_city_namerus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model1CUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=200, verbose_name='Имя 1С пользователя')),
            ],
            options={
                'verbose_name': '1С пользователь',
                'verbose_name_plural': '1С пользователи',
            },
            bases=('user.user',),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=django_fsm.FSMIntegerField(blank=True, choices=[(1, 'Пользователь Компании'), (2, 'Фермер'), (3, 'Поставшик'), (4, 'ЛАБОРАНТ'), (5, '1С ПОЛЬЗОВАТЕЛЬ')], null=True),
        ),
    ]
