# Generated by Django 4.0.3 on 2023-07-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_model1cuser_alter_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='oneC_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='1С ID'),
        ),
    ]
