# Generated by Django 4.0.3 on 2023-09-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_district_onec_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_code',
            field=models.CharField(blank=True, max_length=6, verbose_name='Код для сброса пароля'),
        ),
    ]
