# Generated by Django 4.0.3 on 2023-09-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_reset_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='milkCost',
            field=models.FloatField(default=0, verbose_name='Цена молока'),
        ),
    ]
