# Generated by Django 4.1.4 on 2022-12-30 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_delete_laborantuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaborantUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лаборант',
                'verbose_name_plural': 'Лаборанты',
            },
            bases=('user.user',),
        ),
    ]
