# Generated by Django 4.0.3 on 2022-07-19 23:06

import core.imggenerate
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.imggenerate.all_image_file_path, verbose_name='Фото')),
                ('unit', django_fsm.FSMIntegerField(choices=[(1, 'Килограм'), (2, 'Литр'), (3, 'Count'), (4, 'Метр')], default=2, verbose_name='Измерение')),
                ('type', django_fsm.FSMIntegerField(choices=[(1, 'Активный товар'), (2, 'Неактивный товар')], default=1, verbose_name='Тип товара')),
                ('amountleft', models.FloatField(default=0, verbose_name='Оставшаяся сумма')),
                ('issale', models.BooleanField(default=False, verbose_name='Акция?')),
                ('cost', models.FloatField(default=0, verbose_name='Цена товара')),
                ('costSale', models.FloatField(default=0, verbose_name='Акционная цена товара')),
            ],
        ),
        migrations.CreateModel(
            name='Sort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название cорта')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата')),
                ('totalCost', models.FloatField(default=0, verbose_name='Общая сумма')),
                ('comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='Комментарии')),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_farmer', to='user.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='Accepted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0, verbose_name='Количество')),
                ('unit', django_fsm.FSMIntegerField(choices=[(1, 'Килограм'), (2, 'Литр'), (3, 'Count'), (4, 'Метр')], default=2, verbose_name='Измерение')),
                ('unitCost', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0, verbose_name='Скидка')),
                ('totalCost', models.FloatField(default=0, verbose_name='Общая сумма')),
                ('status', django_fsm.FSMIntegerField(choices=[(1, 'Заплачено'), (2, 'Незаплачено')], default=1, verbose_name='Статус оплаты')),
                ('comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='Комментарии')),
                ('fat', models.FloatField(default=0, verbose_name='Жирность')),
                ('acidity', models.FloatField(default=0, verbose_name='Кислотность')),
                ('distributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.distributer')),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.farmer')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.item')),
                ('sort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.sort')),
            ],
        ),
    ]
