# Generated by Django 4.0.3 on 2022-08-09 06:00

import core.imggenerate
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distributer', '__first__'),
        ('farmer', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.imggenerate.all_image_file_path, verbose_name='Фото')),
                ('unit', django_fsm.FSMIntegerField(choices=[(1, 'Килограм'), (2, 'Литр'), (3, 'Count'), (4, 'Метр')], default=2, verbose_name='Измерение')),
                ('type', django_fsm.FSMIntegerField(choices=[(1, 'Активный товар'), (2, 'Неактивный товар')], default=1, verbose_name='Тип товара')),
                ('amountleft', models.FloatField(default=0, verbose_name='Оставшаяся количество')),
                ('issale', models.BooleanField(default=False, verbose_name='Акция?')),
                ('cost', models.FloatField(default=0, verbose_name='Цена товара')),
                ('costSale', models.FloatField(default=0, verbose_name='Акционная цена товара')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата')),
                ('requirements', models.TextField(blank=True, null=True, verbose_name='Требования')),
                ('responsibilities', models.TextField(blank=True, null=True, verbose_name='Обязанности')),
                ('job_conditions', models.TextField(blank=True, null=True, verbose_name='Условия работы')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=200, null=True, verbose_name='ФИО')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Почта')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Телефон номер')),
            ],
            options={
                'verbose_name': 'Сообщения',
                'verbose_name_plural': 'Сообщении',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=core.imggenerate.all_image_file_path, verbose_name='Фото')),
                ('headline', models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=1, verbose_name='Приоритет')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=core.imggenerate.all_image_file_path, verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдеры',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Sort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название cорта')),
            ],
            options={
                'verbose_name': 'Сорт',
                'verbose_name_plural': 'Сорты',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата')),
                ('video', models.FileField(blank=True, null=True, upload_to=core.imggenerate.all_image_file_path, verbose_name='Видео')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=core.imggenerate.all_image_file_path, verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата')),
                ('totalCost', models.FloatField(default=0, verbose_name='Общая сумма')),
                ('comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='Комментарий')),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_farmer', to='farmer.farmer', verbose_name='Фермер')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Accepted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0, verbose_name='Количество')),
                ('unit', django_fsm.FSMIntegerField(choices=[(1, 'Килограм'), (2, 'Литр'), (3, 'Count'), (4, 'Метр')], default=2, verbose_name='Измерение')),
                ('unitCost', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0, verbose_name='Скидка')),
                ('totalCost', models.FloatField(default=0, verbose_name='Общая сумма')),
                ('status', django_fsm.FSMIntegerField(choices=[(1, 'Заплачено'), (2, 'Незаплачено')], default=1, verbose_name='Статус оплаты')),
                ('comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='Комментарии')),
                ('fat', models.FloatField(default=0, verbose_name='Жирность')),
                ('acidity', models.FloatField(default=0, verbose_name='Кислотность')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата')),
                ('distributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='distributer.distributer', verbose_name='Дистрибьютер')),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer.farmer', verbose_name='Фермер')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.item', verbose_name='Товар')),
                ('sort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.sort')),
            ],
            options={
                'verbose_name': 'Принятый продукт',
                'verbose_name_plural': 'Принятые продукты',
                'ordering': ('-id',),
            },
        ),
    ]
