# Generated by Django 4.0.3 on 2022-08-08 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_farmer_payment_left_alter_farmer_verified_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salefarmercategory',
            options={'ordering': ('-id',), 'verbose_name': 'Категория продукт для продажи фермерам', 'verbose_name_plural': 'Категории продукт для продажи фермерам'},
        ),
        migrations.AlterModelOptions(
            name='salefarmeritem',
            options={'ordering': ('-id',), 'verbose_name': 'Продукт для продажи фермерам', 'verbose_name_plural': 'Продукты для продажи фермерам'},
        ),
        migrations.AlterModelOptions(
            name='webproducts',
            options={'ordering': ('-id',), 'verbose_name': 'Товар для ВЕБ', 'verbose_name_plural': 'Товары для ВЕБ'},
        ),
        migrations.AlterField(
            model_name='accepted',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.distributer', verbose_name='Дистрибьютер'),
        ),
        migrations.AlterField(
            model_name='accepted',
            name='farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.farmer', verbose_name='Фермер'),
        ),
        migrations.AlterField(
            model_name='accepted',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.item', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='item',
            name='amountleft',
            field=models.FloatField(default=0, verbose_name='Оставшаяся количество'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_farmer', to='user.farmer', verbose_name='Фермер'),
        ),
        migrations.AlterField(
            model_name='salefarmeritem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.salefarmercategory', verbose_name='Категория'),
        ),
    ]
