# Generated by Django 4.0.3 on 2022-08-08 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_salefarmercategory_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebProducts',
        ),
    ]
