# Generated by Django 4.0.3 on 2022-07-21 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_job_messages_news_slider_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='сonditions',
            new_name='job_conditions',
        ),
    ]
