# Generated by Django 4.0.3 on 2022-08-02 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_сonditions_job_job_conditions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accepted',
            options={'ordering': ('-id',), 'verbose_name': 'Принятый продукт', 'verbose_name_plural': 'Принятые продукты'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('-id',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('-id',), 'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ('-id',), 'verbose_name': 'Сообщения', 'verbose_name_plural': 'Сообщении'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-id',), 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-id',), 'verbose_name': 'Оплата', 'verbose_name_plural': 'Оплаты'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ('-id',), 'verbose_name': 'Слайдер', 'verbose_name_plural': 'Слайдеры'},
        ),
        migrations.AlterModelOptions(
            name='sort',
            options={'ordering': ('-id',), 'verbose_name': 'Сорт', 'verbose_name_plural': 'Сорты'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ('-id',), 'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
    ]
