# Generated by Django 4.0.3 on 2022-08-08 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
        ('core', '0003_delete_webproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accepted',
            name='farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer.farmer', verbose_name='Фермер'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_farmer', to='farmer.farmer', verbose_name='Фермер'),
        ),
    ]
