# Generated by Django 4.0.3 on 2022-08-03 05:57

import core.imggenerate
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_accepted_options_alter_item_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleFarmerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameRu', models.CharField(max_length=500, verbose_name='Название на русском')),
                ('nameKg', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название на кыргызском')),
                ('nameEn', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название на английском')),
            ],
        ),
        migrations.CreateModel(
            name='WebProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.imggenerate.all_image_file_path, verbose_name='Фото')),
                ('category', django_fsm.FSMIntegerField(choices=[(1, 'Молочная продукция'), (2, 'Национальные напитки'), (3, 'Прохладные напитки')], verbose_name='Категория')),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=core.imggenerate.all_image_file_path, verbose_name='Фото'),
        ),
        migrations.CreateModel(
            name='SaleFarmerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('cost', models.FloatField(default=0, verbose_name='Цена')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.imggenerate.all_image_file_path, verbose_name='Фото')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.salefarmercategory')),
            ],
        ),
    ]
