# Generated by Django 4.0.3 on 2023-06-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_payment_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='accepted',
            name='sync_with_oneC',
            field=models.BooleanField(default=False, verbose_name='Статус синхронизации с 1С'),
        ),
    ]
