# Generated by Django 4.0.3 on 2023-06-20 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_accepted_sync_with_onec'),
    ]

    operations = [
        migrations.AddField(
            model_name='accepted',
            name='ref',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='oneC_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='1С ID'),
        ),
    ]
