# Generated by Django 4.0.3 on 2022-08-08 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributer', '0001_initial'),
        ('core', '0005_remove_salefarmeritem_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accepted',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='distributer.distributer', verbose_name='Дистрибьютер'),
        ),
    ]
