# Generated by Django 4.0.3 on 2023-08-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_accepted_date_second'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accepted',
            name='date_second',
            field=models.DateField(auto_now=True, null=True, verbose_name='Дата срока'),
        ),
    ]
