# Generated by Django 4.0.3 on 2023-08-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_accepted_date_second'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accepted',
            name='date_second',
            field=models.CharField(blank=True, max_length=100, verbose_name='Дата срока'),
        ),
    ]
