# Generated by Django 4.0.3 on 2023-08-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_accepted_date_second'),
    ]

    operations = [
        migrations.AddField(
            model_name='accepted',
            name='date_other',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дата срока'),
        ),
    ]
