# Generated by Django 4.0.3 on 2023-08-26 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_accepted_date_other'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accepted',
            name='date_second',
        ),
    ]
