# Generated by Django 4.0.3 on 2023-08-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_accepted_date_second'),
    ]

    operations = [
        migrations.AddField(
            model_name='accepted',
            name='date_second',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
