# Generated by Django 4.0.3 on 2023-08-28 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_accepted_date_second'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accepted',
            name='date_other',
        ),
    ]
